name: UI Patterns Settings
type: module
description: Configure patterns with settings
core: 8.x
package: User interface
core_version_requirement: ^8 || ^9
dependencies:
  - ui_patterns:ui_patterns
  - token:token
