widget:
  version: VERSION
  js:
    js/ui_pattern_settings.toggle_token.js: {}
  css:
    component:
      css/ui_patterns_settings.css: {}
  dependencies:
    - core/jquery
    - core/jquery.once
    - core/drupal
    - core/drupalSettings
