ui_patterns_settings.settings:
  type: config_object
  label: 'UI Patterns settings config'
  mapping:
    mapping:
      type: sequence
      label: 'Mapping'
      sequence:
        type: string
        label: 'Field mapping'
